### ISSUE TITLE
Atrributes are incorrect if equals sign is in attribute

### ISSUE THREAD

**Issue by ibinsfei** [matanshiloah/xml-parser#16]
The parsing of attributes splits by the equal sign '='
If an attibute contains a equals sign the attributes are parsed incorrect.
Example:
<newpage name="Interesting" url="https://www.aaa.bb/page.htm?no=4&next=7"/>
=> atrributes: {name: "Interesting", url: "https://www.aaa.bb/page.htm?no"}

**Comment by EmersonFJ** [comment]
@ibinsfei @matanshiloah 

Having the same issue - did you find a work around / way to deal with this? 

Example:
Should be: attributes: {url:"../ix?doc=https://www.link.com}
Returns: attributed: {url:".../ix?doc"}

So missing the "=" and everything to the right. Will circle back if I find a way around it

**Comment by matanshiloah** [comment]
Fixed parsing for attributes with equal side in value (v1.1.1)
