### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by JayAshday** [matanshiloah/xml-parser#18]
It appears that because this package uses a JavaScript class in its distributable code, it is not compatible with Internet Explorer 11 (which doesn't support classes). Since some institutions still need to support this browser, it would be good to either A) Adjust this package to function properly in IE11; or B) Include a note about what browsers are supported in the documentation.

I'd certainly prefer option A), but option B) would at least be enough to hopefully prevent other people who need IE11 support from implementing this package and then needing to track down why their site isn't working.

**Comment by matanshiloah** [comment]
Added babel to solve this issue (v1.1.0)

**Comment by JayAshday** [comment]
Great, thank you!
