### ISSUE TITLE
Read From File

### ISSUE THREAD

**Issue by shuhratjan** [matanshiloah/xml-parser#28]
Hello dear author, your code is so friendly to use, thank you for that!
My question: Could you show how to read from File(data.xml), then parse it?
In your example, you parsed from stringXML into react variable.

**Comment by matanshiloah** [comment]
Server side:
    
    const XMLParser = require('react-xml-parser');

    const fs = require('fs');

    fs.readFile('data.xml', (err, data) => {

        const xml = new XMLParser().parseFromString(data);    // parsing the xml content from data.xml

    });

If you are allowing user to upload file on client side, you can use this example for the loader: https://stackoverflow.com/questions/16505333/get-the-data-of-uploaded-file-in-javascript.
Then parse the file content from string.
