### ISSUE TITLE
Updating the regex string

### ISSUE THREAD

**Issue by onkar-agarwal** [matanshiloah/xml-parser#33]
Hi
Thanks for creating this.
I am using this and I found out that the regex checking you are doing in "_encodeCDATAValues" should be modified to **/<!\[CDATA\[([^\]\]]+)\]\]>/gi**

Actual cdata is written `<![CDATA[]]>` like this.
Thanks again.

**Comment by matanshiloah** [comment]
Thanks for the feedback, fixed in v1.1.8
