### ISSUE TITLE
Unable to compile during 'react-scripts run build'

### ISSUE THREAD

**Issue by tbowdollar** [matanshiloah/xml-parser#7]
The error: Unexpected token: punc ({) [./~/react-xml-parser/xmlParser.js:1,0][static/js/main.4ad9ac20.js:27520,23]

**Comment by tbowdollar** [comment]
any update please?

**Comment by arturrobbins** [comment]
I have the same issue, when compiling it, got this error : 

fail to minify this module: react-xml-parser

**Comment by matanshiloah** [comment]
I have created a branch with a fix - using webpack for building (issue#7).
I want to publish it to npm as a side version, just to see if it works for you, I don't want to have issues with backward compatibility. 
Does anyone of the issue followers knows if it is possible and how I can do this?

**Comment by arturrobbins** [comment]
I solved it by implementing it directly in the app and just copy paste the content of the package in the app, and work perfectly.

**Comment by matanshiloah** [comment]
This makes sense, but now you are not aware of new updates to the libraery

**Comment by nexthor** [comment]
> I solved it by implementing it directly in the app and just copy paste the content of the package in the app, and work perfectly.

i aint find any other solution than this one, and works perfectly! thank you so much!

**Comment by matanshiloah** [comment]
Added webpack + babel to fix this issue (v1.1.0)
