### ISSUE TITLE
Unable to grab tags with colon in the name after upgrade to 1.0.4

### ISSUE THREAD

**Issue by catslug** [matanshiloah/xml-parser#8]
Hi there,

I've been using 1.0.3 to parse part of an rss feed with tags styled like `<title:subtitle>`. Since the new release, the feed hasn't been identifying text that follows the colon. 

Tags that follow the format `<title:subtitle1>`, `<title:subtitle2>`, etc.  have to all be accessed by calling `xml.getElementsByTagName('title')`. The result returns an array of items all listed by the same name, so it's impossible to guarantee you'll grab the value you need. It's dependent on the order of items, which is brittle and unreliable. Trying to grab the tag name by `xml.getElementsByTagName('title:subtitle')` returns an empty array; trying to grab the value returns `undefined`. 

The item I'm trying to parse from the feed:
```
<itunes:duration>00:32:11</itunes:duration>
```

Was working steadily prior to the new release: 
``` 
duration: xml.getElementsByTagName('itunes:duration')[0].value,   // returns undefined 
```

Currently the only way to access the value in the first part of the tag: 
``` 		
duration: xml.getElementsByTagName('itunes'),  // returns an array of 6 items without access to the trailing identifiers
```

**Comment by matanshiloah** [comment]
Fixed in version 1.0.5.
